### ISSUE TITLE
When is this getting an update?

### ISSUE THREAD

**Issue by bentaylor776** [leanix/leanix-sdk-csharp#2]
There are large gaps in the SDK compared the web services especially now the ifaces object has appeared.  Is there going to be a centralised update or do I keep hand cranking code?

**Comment by dllx** [comment]
Yes, this SDK is rather old and there have been many additions to leanIX in the meantime.
Right now, we are a bit tight on schedule, but we'll look into it during the next two weeks to decide when we can supply a new version adapted to the REST API of leanIX 2.0.
Please comment if you need an update more urgently.

**Comment by bentaylor776** [comment]
I have heavily modified my local version of the SDK to get it work with the additional features of 2.0 including IFace, but I'd like to get back to the main Fork. I am more interested in understanding release dates so I can plan my time to migrate.

**Comment by andrechrist** [comment]
Hi @bentaylor776 , thank you very much for your interest in the SDK. We have updated the SDK to the latest version of leanIX now. We are using a template based approached (using swagger-codegen) here, so you could even do it yourself easily by running mvn package (requires to install maven).

I have committed the update into the develop branch, as I have not yet run a full test on all parts and I didn't have Visual Studio on hand on the machine I'm using at this place. Therefore it could be, that the Projects-Files needs an update.

Looking forward to your answer,
André
